name: GCP Authenticate
description: Authenticate with Google Cloud Platform

inputs:
  credentials_file:
    description: Google's credenetials JSON file encoded
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4

    - name: Decode and Write JSON File
      shell: bash
      run: |
        mkdir -p $HOME/.config/gcloud/
        echo "${{ inputs.credentials_file }}" | base64 -d > $HOME/.config/gcloud/application_default_credentials.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/.config/gcloud/application_default_credentials.json" >> "$GITHUB_ENV"
        cat $HOME/.config/gcloud/application_default_credentials.json

    - name: Authenticate With Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.credentials_file }}

    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: latest

    - name: Set gcloud Project
      shell: bash
      run: gcloud config set project $(cat "${{ inputs.credentials_file }}" | base64 -d | jq '.project_id')
