name: "Convert to Lowercase"
description: "Convert input to lowercase"
inputs:
  text:
    description: "Text to convert to lowercase"
    required: true
outputs:
  result:
    description: "Lowercase repository name"
    value: ${{ steps.to_lower_case.outputs.converted_text }}
runs:
  using: "composite"
  steps:
    - name: Convert to lowercase
      id: to_lower_case
      shell: bash
      run: |
        input_text="${{ inputs.text }}"
        input_text=$(echo "$input_text" | tr '[:upper:]' '[:lower:]')
        echo "converted_text=$input_text" >> $GITHUB_OUTPUT
        echo ${{ converted_text }}
