name: "Convert to Lowercase"
description: "Convert input to lowercase"
inputs:
  text:
    description: "Text to convert to lowercase"
    required: true
outputs:
  result:
    description: "Lowercase repository name"
    value: "Hello World"
runs:
  using: "composite"
  steps:
    - name: Convert to lowercase
      id: to_lowercase
      shell: bash
      run: |
        converted_text=$(echo "${{ inputs.text }}" | tr '[:upper:]' '[:lower:]')
        echo "converted_text=$converted_text" >> $GITHUB_OUTPUT
        echo "CONVERTED_TEXT=$converted_text" >> $GITHUB_ENV
        echo ${{ converted_text }}
