name: "Convert to Lowercase"
description: "Convert input to lowercase"
inputs:
  text:
    description: "Text to convert to lowercase"
    required: true
  env_var:
    description: "Environment variable to assign to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Convert to lowercase
      shell: bash
      run: |
        echo -e "env_var is ${{ inputs.env_var }}\ntext is ${{ inputs.text }}"
        input_to_convert=$(echo "${{ inputs.text }}" | tr '[:upper:]' '[:lower:]')
        echo "$env_var=$input_to_convert" >> $GITHUB_ENV
