name: "Convert to Lowercase"
description: "Convert input to lowercase"
inputs:
  text:
    description: "Text to convert to lowercase"
    required: true
outputs:
  result:
    description: "Lowercase repository name"
    value: "Hello World"
runs:
  using: "composite"
  steps:
    - name: Convert to lowercase
      id: to_lowercase
      shell: bash
      run: |
        fuckin_txt=$(echo "${{ inputs.text }}" | tr '[:upper:]' '[:lower:]')
        echo "converted_text=$fuckin_txt" >> $GITHUB_OUTPUT
        echo "CONVERTED_TEXT=$fuckin_txt" >> $GITHUB_ENV
        echo ${{ fuckin_txt }}
