name: "Convert to Lowercase"
description: "Convert input to lowercase"
inputs:
  text:
    description: "Text to convert to lowercase"
    required: true
outputs:
  result:
    description: "Lowercase repository name"
    value: "Hello World"
runs:
  using: "composite"
  steps:
    - name: Convert to lowercase
      shell: bash
      run: |
        fuckin_txt=$(echo "${{ inputs.text }}" | tr '[:upper:]' '[:lower:]')
        echo "DEFAULTENVVAR=$fuckin_txt" >> $GITHUB_ENV
